In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
moviesData = pd.read_csv('wiki_movies.csv')

In [3]:
moviesData.shape

(34886, 8)

In [4]:
moviesData.head(10)

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...
5,1903,Alice in Wonderland,American,Cecil Hepworth,May Clark,unknown,https://en.wikipedia.org/wiki/Alice_in_Wonderl...,"Alice follows a large white rabbit down a ""Rab..."
6,1903,The Great Train Robbery,American,Edwin S. Porter,NaN,western,https://en.wikipedia.org/wiki/The_Great_Train_...,The film opens with two bandits breaking into ...
7,1904,The Suburbanite,American,Wallace McCutcheon,NaN,comedy,https://en.wikipedia.org/wiki/The_Suburbanite,The film is about a family who move to the sub...
8,1905,The Little Train Robbery,American,Edwin Stanton Porter,NaN,unknown,https://en.wikipedia.org/wiki/The_Little_Train...,The opening scene shows the interior of the ro...
9,1905,The Night Before Christmas,American,Edwin Stanton Porter,NaN,unknown,https://en.wikipedia.org/wiki/The_Night_Before...,Scenes are introduced using lines of the poem....

In [5]:
# TotalCount column added to facilitate aggregation
moviesData['TotalCount'] = 1

In [6]:
totalNumberOfGenres = moviesData[['Genre','TotalCount']].groupby(['Genre'], as_index=False).count().shape[0]

In [7]:
totalNumberOfGenres

2265

In [8]:
# There are 2265 different genres (classes)
# There are too many classes for an ML model
# Also some classes have very few observations

In [9]:
##### Data Cleaning #######

In [10]:
# new column to perform genre modification
moviesData['Edited_Genre'] = moviesData['Genre']

In [11]:
# remove all leading and trailing whitespaces
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.strip()

In [12]:
# replace punctuations with pipeline
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' - ', '|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' / ', '|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('/', '|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' & ', '|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(', ', '|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('; ', '|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' ','|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(',','|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\|\|','|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\|–\|','|')

In [13]:
# modifying all the biography related genre into just 'biography'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('bio-pic', 'biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biopic', 'biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biographical', 'biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biodrama', 'biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('bio-drama', 'biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biographic', 'biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biography about montreal canadiens star|maurice richard','biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biography of pioneering american photographer eadweard muybridge','biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biography fim','biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biogtaphy','biography')

In [14]:
# modifying all the history related genre into just 'history'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('historical','history')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('historic','history')

In [15]:
# replacing all the unnecessary noise in genre data to empty string
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \(film genre\)', '')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\[not in citation given\]','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' set 4,000 years ago in the canadian arctic','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('viacom 18 motion pictures','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('.','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('based on radio serial','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' on the early years of hitler','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' (30min)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\[144\]','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' for ','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('bholenath movies|cinekorn entertainment','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \(volleyball\)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('films','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('film','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('british-german co-production','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('movies by the mob\|knkspl','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('movies','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('movie','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('(( based).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('(( co-produced).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('(( adapted).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('(( about).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \(aquatics|swimming\)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \(aquatics|swimming\)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace("yogesh dattatraya gosavi's directorial debut \[9\]",'')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('unknown','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\|007','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \(shogi|chess\)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\|6 separate stories','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \(30min\)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' (road bicycle racing)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' v-cinema','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('((adaptation).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('((adaptated).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('((adapted).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('(( on ).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \(artistic\)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \|direct-to-dvd','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\|1 girl\|3 suitors','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' \(road bicycle racing\)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('-','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\|\(children\|poker\|karuta\)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('((\|produced\|).+)','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('colour\|yellow\|productions\|eros\|international','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\|directtodvd','')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('social','')

In [16]:
# modifying all the animation related genre into just 'animation'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('animated','animation')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('anime','animation')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('3-d','animation')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('3d','animation')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('computer animation','animation')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' in animation','|animation')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('computeranimation','animation')

In [17]:
# modifying all the genre about children into just 'children'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('children\'s','children')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('family','children')

In [18]:
# modifying all the comedy related genre into just 'comedy'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('comedey','comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('comedy 2-reeler','comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('heistcomedy','comedy')

In [19]:
# modifying all the romance related genre into just 'romance'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('romantic','romance')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('rom-coms','romance')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('romanctic','romance')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('romantic','romance')

In [20]:
# modifying all the science_fiction related genre into just 'science_fiction'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('sci-fi','science_fiction')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('sci fi','science_fiction')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('science fiction','science_fiction')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('sciencefiction','science_fiction')

In [21]:
# cleaning up some extra genres
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('16 mm film','short')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('adventures','adventure')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('anthology film','anthology')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('avant-garde','avant_garde')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biker film','biker')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('buddy cop','buddy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('buddy film','buddy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('coming of age','coming_of_age')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('coming-of-age','coming_of_age')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('musical b','musical')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace(' period','period')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('periodic','period')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('psychological','psycho')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('true crime','crime')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('slice of life','slice_of_life')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('j-horror','horror')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('chanbara','chambara')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('fantay','fantasy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('satirical','satire')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('politics','political')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('mockumentary','documentary')

In [22]:
# modifying all the drama related genre into just 'drama'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\[140\]','drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('drama about child soldiers','drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('drama loosely','drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('melodrama','drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('dramatic','drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('dramaa','drama')

In [23]:
# cleaning up all the multi genres
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('comedy-drama adaptation of the mordecai richler novel','comedy-drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('animationchildren','animation|children')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('afghan war drama','war drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('\|docudrama','\|documentary|drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('history dram','history drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('psycho thriller,','psycho thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('actionadventure','action|adventure')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('actioncomedy','action|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('actiondrama','action|drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('actionlove','action|love')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('actionmasala','action|masala')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('actionchildren','action|children')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('fantasychildren\|','fantasy|children')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('fantasycomedy','fantasy|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('fantasyperiod','fantasy|period')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('dramacomedy','drama|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('dramacomedysocial','drama|comedy|social')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('dramathriller','drama|thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('comedydrama','comedy|drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('dramathriller','drama|thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('comedyhorror','comedy|horror')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('adventurecomedy','adventure|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('animationdrama','animation|drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('crimethriller','crime|thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('actionthriller','action|thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('comedysocial','comedy|social')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('epichistory','epic|history')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('comedythriller','comedy|thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('liveaction','live|action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('historydisaster','history|disaster')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('warcomedy','war|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('westerncomedy','western|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('dramedy','drama|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('devotionalbiography','devotional|biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('docufiction','documentary|fiction')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('familydrama','family|drama')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('romancefiction','romance|fiction')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('horrorthriller','horror|thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('suspensethriller','suspense|thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('musicaliography','musical|biography')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('romanceaction','romance|action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('romancecomedy','romance|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('romancehorror','romance|horror')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('romcom','romance|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('rom\|com','romance|comedy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('science_fictionchildren','science_fiction|children')

In [24]:
# modifying all the thriller related genre into just 'thriller'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('ttriller','thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('thriler','thriller')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('triller','thriller')

In [25]:
# modifying all the martial arts related genre into just 'martial_arts'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('kung fu','martial_arts')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('kung-fu','martial_arts')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('martial arts','martial_arts')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('bruceploitation','martial_arts')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('gun fu','martial_arts')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('martial art','martial_arts')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('martialarts','martial_arts')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('samurai','martial_arts')

In [26]:
# modifying all the war related genre into just 'war'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('world war ii','war')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('world war i','war')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace("war-time","war")
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace("wartime","war")
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace("ww1","war")
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace("wwii","war")

In [27]:
# modifying all the tv miniseries related genre into just 'tv_miniseries'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('tv miniseries','tv_miniseries')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('television miniseries','tv_miniseries')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('cbctv_miniseries','tv_miniseries')

In [28]:
# modifying all the spy related genre into just 'spy'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('spy film','spy')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('espionage','spy')

In [29]:
# modifying all the sports related genre into just 'sports'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('american football','sports')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('dev\|nusrat jahan','sports')

In [30]:
# modifying all the adult related genre into just 'adult'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('erotica','adult')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('erotic','adult')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('homosexual','adult')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('sexual','adult')

In [31]:
# modifying all the religious genre into just 'religious'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('muslim','religious')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biblical','religious')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('biblical','religious')

In [32]:
# modifying all the superhero related genre into just 'superhero'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('superheroes','superhero')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('superheroe','superhero')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('supeheroes','superhero')

In [33]:
# modifying all the family related genre into just 'family'
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('familya','family')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('familya','family')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('famil\|','family')

In [34]:
# Conditionally modifying and cleaning up genres in a bunch
moviesData.loc[moviesData['Edited_Genre']=="ero",'Edited_Genre']="adult"
moviesData.loc[moviesData['Edited_Genre']=="music",'Edited_Genre']="musical"
moviesData.loc[moviesData['Edited_Genre']=="-",'Edited_Genre']=''
moviesData.loc[moviesData['Edited_Genre']=="comedy–drama",'Edited_Genre'] = "comedy|drama"
moviesData.loc[moviesData['Edited_Genre']=="comedy–horror",'Edited_Genre'] = "comedy|horror"
moviesData.loc[moviesData['Edited_Genre']=="musical–comedy",'Edited_Genre'] = "musical|comedy"
moviesData.loc[moviesData['Edited_Genre']=="roman|porno",'Edited_Genre'] = "adult"
moviesData.loc[moviesData['Edited_Genre']=="action—masala",'Edited_Genre'] = "action|masala"
moviesData.loc[moviesData['Edited_Genre']=="horror–thriller",'Edited_Genre'] = "horror|thriller"
moviesData.loc[moviesData['Edited_Genre']=="drama|romance|adult|children",'Edited_Genre'] = "drama|romance|adult"

In [35]:
# merging some of the genres with less data into one


moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('social','')


# to <unknown> genre
moviesData.loc[moviesData['Edited_Genre']=="",'Edited_Genre'] = "<unknown>"

# to series
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('tv_miniseries','series')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('serial','series')

# to children
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('family','children')
moviesData.loc[moviesData['Edited_Genre']=="children|drama",'Edited_Genre'] = "children"
moviesData.loc[moviesData['Edited_Genre']=="children|fantasy",'Edited_Genre'] = "children"

# to thriller
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('horror','thriller')
moviesData.loc[moviesData['Edited_Genre']=="thriller|thriller",'Edited_Genre'] = "thriller"
moviesData.loc[moviesData['Edited_Genre']=="thriller|action",'Edited_Genre'] = "thriller"
moviesData.loc[moviesData['Edited_Genre']=="thriller|comedy",'Edited_Genre'] = "thriller"
moviesData.loc[moviesData['Edited_Genre']=="thriller|drama",'Edited_Genre'] = "thriller"
moviesData.loc[moviesData['Edited_Genre']=="thriller|romance|comedy",'Edited_Genre'] = "thriller"


# to black
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('noir','black')
moviesData.loc[moviesData['Edited_Genre']=="black|comedy",'Edited_Genre'] = "black"



# to action
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('war','action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('adventure','action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('western','action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('spy','action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('martial_arts','action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('superhero','action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('suspense','action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('slasher','action')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.replace('slahser','action')
moviesData.loc[moviesData['Edited_Genre']=="action|action",'Edited_Genre'] = "action"
moviesData.loc[moviesData['Edited_Genre']=="action|biography",'Edited_Genre'] = "action"
moviesData.loc[moviesData['Edited_Genre']=="action|comedy",'Edited_Genre'] = "action"
moviesData.loc[moviesData['Edited_Genre']=="action|drama",'Edited_Genre'] = "action"
moviesData.loc[moviesData['Edited_Genre']=="action|romance",'Edited_Genre'] = "action"
moviesData.loc[moviesData['Edited_Genre']=="action|thriller",'Edited_Genre'] = "action"
moviesData.loc[moviesData['Edited_Genre']=="world|action|ii",'Edited_Genre'] = "action"



# to animation
moviesData.loc[moviesData['Edited_Genre']=="animation|children",'Edited_Genre'] = "animation"
moviesData.loc[moviesData['Edited_Genre']=="animation|short",'Edited_Genre'] = "animation"
moviesData.loc[moviesData['Edited_Genre']=="animation|feature",'Edited_Genre'] = "animation"
moviesData.loc[moviesData['Edited_Genre']=="animation|action",'Edited_Genre'] = "animation"
moviesData.loc[moviesData['Edited_Genre']=="animation|comedy",'Edited_Genre'] = "animation"

# to biography
moviesData.loc[moviesData['Edited_Genre']=="biography|drama",'Edited_Genre'] = "biography"
moviesData.loc[moviesData['Edited_Genre']=="biography|musical",'Edited_Genre'] = "biography"
moviesData.loc[moviesData['Edited_Genre']=="biography|sports",'Edited_Genre'] = "biography"

# to comedy
moviesData.loc[moviesData['Edited_Genre']=="comedy|action",'Edited_Genre'] = "comedy"
moviesData.loc[moviesData['Edited_Genre']=="comedy|children",'Edited_Genre'] = "comedy"
moviesData.loc[moviesData['Edited_Genre']=="comedy|crime",'Edited_Genre'] = "comedy"

moviesData.loc[moviesData['Edited_Genre']=="comedy|drama|romance",'Edited_Genre'] = "comedy|drama"
moviesData.loc[moviesData['Edited_Genre']=="comedy|fantasy",'Edited_Genre'] = "comedy|drama"


moviesData.loc[moviesData['Edited_Genre']=="comedy|romance",'Edited_Genre'] = "romance|comedy"

# to crime
moviesData.loc[moviesData['Edited_Genre']=="crime|drama",'Edited_Genre'] = "crime"
moviesData.loc[moviesData['Edited_Genre']=="crime|comedy",'Edited_Genre'] = "crime"
moviesData.loc[moviesData['Edited_Genre']=="crime|thriller",'Edited_Genre'] = "crime"


# to musical
moviesData.loc[moviesData['Edited_Genre']=="musical|comedy",'Edited_Genre'] = "musical"
moviesData.loc[moviesData['Edited_Genre']=="musical|drama",'Edited_Genre'] = "musical"

# to romance
moviesData.loc[moviesData['Edited_Genre']=="romance|drama",'Edited_Genre'] = "romance"
moviesData.loc[moviesData['Edited_Genre']=="drama|romance",'Edited_Genre'] = "romance"

# to science|fiction
moviesData.loc[moviesData['Edited_Genre']=="scifi",'Edited_Genre'] = "science|fiction"

In [36]:
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.strip(to_strip='\|')
moviesData['Edited_Genre']=moviesData['Edited_Genre'].str.strip()

In [37]:
moviesData[['Edited_Genre','TotalCount']].groupby(['Edited_Genre'], as_index=False).count().shape[0]

1358

In [38]:
moviesData[['Edited_Genre','TotalCount']].groupby(['Edited_Genre'],as_index=False).count().sort_values(['TotalCount'], ascending=False).head(20)

         Edited_Genre  TotalCount
1           <unknown>        6201
555             drama        6093
383            comedy        4555
2              action        3886
1257         thriller        2338
1064          romance        1342
481             crime        1216
216         animation         758
1074   romance|comedy         689
935           musical         666
1135  science|fiction         641
413      comedy|drama         603
318             black         397
343          children         363
954           mystery         310
287         biography         297
749           fantasy         204
558      drama|action         132
546       documentary         105
818           history          85

In [39]:
moviesGenre = moviesData[['Edited_Genre','TotalCount']].groupby(['Edited_Genre']).count()
moviesGenre.to_csv('GenreCorrected.csv',sep=',')

In [40]:
# moviesData['Split_Genre']=moviesData['Edited_Genre'].str.split('|')
moviesData['Edited_Genre']= moviesData['Edited_Genre'].apply(np.unique)

In [41]:
moviesData['Edited_Genre'][11]

array(['short|action|crime|action'], dtype='<U25')

In [42]:
# Number of movies in each genre

genresArr = np.array([])

for i in range(0,moviesData.shape[0]-1):
    genresArr = np.concatenate((genresArr, moviesData['Edited_Genre'][i] ))

    
genresData = pd.DataFrame({'Genre':genresArr})

In [43]:
genresData.head(10)

       Genre
0  <unknown>
1  <unknown>
2  <unknown>
3  <unknown>
4  <unknown>
5  <unknown>
6     action
7     comedy
8  <unknown>
9  <unknown>

In [44]:
genresData['Count']=1
genresData[['Genre','Count']].groupby(['Genre'], as_index=False).sum().sort_values(['Count'], ascending=False).head(15)

                Genre  Count
1           <unknown>   6201
555             drama   6093
383            comedy   4555
2              action   3886
1257         thriller   2338
1064          romance   1341
481             crime   1216
216         animation    758
1074   romance|comedy    689
935           musical    666
1135  science|fiction    641
413      comedy|drama    603
318             black    397
343          children    363
954           mystery    310

In [45]:
# selection of genre for classification

genresData=genresData[['Genre','Count']].groupby(['Genre'], as_index=False).sum().sort_values(['Count'], ascending=False)

genresData = genresData[genresData['Genre']!='<unknown>']
genresData.head(25)

                Genre  Count
555             drama   6093
383            comedy   4555
2              action   3886
1257         thriller   2338
1064          romance   1341
481             crime   1216
216         animation    758
1074   romance|comedy    689
935           musical    666
1135  science|fiction    641
413      comedy|drama    603
318             black    397
343          children    363
954           mystery    310
287         biography    297
749           fantasy    204
558      drama|action    132
546       documentary    105
818           history     85
457   comedy|thriller     78
613      drama|comedy     74
438    comedy|musical     71
1178           series     71
640       drama|crime     69
719    drama|thriller     65

In [46]:
# calculating the frequency and cumulative frequency of the genres
totalMovies=sum(genresData['Count'])
genresData['Frequency'] = genresData['Count']/totalMovies
genresData['CumulativeFrequency'] = genresData['Frequency'].cumsum()

In [47]:
genresData.head(25)

                Genre  Count  Frequency  CumulativeFrequency
555             drama   6093   0.212418             0.212418
383            comedy   4555   0.158799             0.371217
2              action   3886   0.135476             0.506694
1257         thriller   2338   0.081509             0.588202
1064          romance   1341   0.046751             0.634953
481             crime   1216   0.042393             0.677346
216         animation    758   0.026426             0.703772
1074   romance|comedy    689   0.024020             0.727792
935           musical    666   0.023219             0.751011
1135  science|fiction    641   0.022347             0.773358
413      comedy|drama    603   0.021022             0.794380
318             black    397   0.013840             0.808221
343          children    363   0.012655             0.820876
954           mystery    310   0.010807             0.831683
287         biography    297   0.010354             0.842037
749           fantasy    204   0.007112             0.849149
558      drama|action    132   0.004602             0.853751
546       documentary    105   0.003661             0.857412
818           history     85   0.002963             0.860375
457   comedy|thriller     78   0.002719             0.863094
613      drama|comedy     74   0.002580             0.865674
438    comedy|musical     71   0.002475             0.868149
1178           series     71   0.002475             0.870625
640       drama|crime     69   0.002406             0.873030
719    drama|thriller     65   0.002266             0.875296

In [48]:
# we will select genres with cum freq of  87.6% or below
selectedGenres=np.array(genresData[genresData['CumulativeFrequency']<=.876]['Genre'])
moviesData['Selected_Genre'] = moviesData['Edited_Genre'].apply(lambda x: x[np.in1d(x,selectedGenres)])

In [49]:
moviesData[['Selected_Genre','Edited_Genre','Genre']][10:20]

   Selected_Genre                 Edited_Genre                       Genre
10             []                      [short]                       short
11             []  [short|action|crime|action]  short action/crime western
12             []                      [short]                  short film
13    [biography]                  [biography]                biographical
14       [comedy]                     [comedy]                      comedy
15       [comedy]                     [comedy]                      comedy
16        [drama]                      [drama]                       drama
17        [drama]                      [drama]                       drama
18       [comedy]                     [comedy]                      comedy
19       [action]                     [action]                   adventure

In [50]:
# initial cleaning of the plot of movies
def cleanPlot(plot):
    plot = plot.lower()
    plot = re.sub(r"what's", "what is ", plot)
    plot = re.sub(r"\'s", " ", plot)
    plot = re.sub(r"\'ve", " have ", plot)
    plot = re.sub(r"can't", "can not ", plot)
    plot = re.sub(r"n't", " not ", plot)
    plot = re.sub(r"i'm", "i am ", plot)
    plot = re.sub(r"\'re", " are ", plot)
    plot = re.sub(r"\'d", " would ", plot)
    plot = re.sub(r"\'ll", " will ", plot)
    plot = re.sub(r"\'scuse", " excuse ", plot)
    plot = plot.strip(' ')
    return plot

In [51]:
moviesData['Clean_Plot'] = moviesData['Plot'].apply(cleanPlot)

In [52]:
moviesData[['Plot','Clean_Plot','Selected_Genre']][5:10]

,Plot,Clean_Plot,Selected_Genre
5,"Alice follows a large white rabbit down a ""Rab...","alice follows a large white rabbit down a ""rab...",[]
6,The film opens with two bandits breaking into ...,the film opens with two bandits breaking into ...,[action]
7,The film is about a family who move to the sub...,the film is about a family who move to the sub...,[comedy]
8,The opening scene shows the interior of the ro...,the opening scene shows the interior of the ro...,[]
9,Scenes are introduced using lines of the poem....,scenes are introduced using lines of the poem....,[]

In [53]:
moviesData.head(25)

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot,TotalCount,Edited_Genre,Selected_Genre,Clean_Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr...",1,[<unknown>],[],"a bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov...",1,[<unknown>],[],"the moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed...",1,[<unknown>],[],"the film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...,1,[<unknown>],[],lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...,1,[<unknown>],[],the earliest known adaptation of the classic f...
5,1903,Alice in Wonderland,American,Cecil Hepworth,May Clark,unknown,https://en.wikipedia.org/wiki/Alice_in_Wonderl...,"Alice follows a large white rabbit down a ""Rab...",1,[<unknown>],[],"alice follows a large white rabbit down a ""rab..."
6,1903,The Great Train Robbery,American,Edwin S. Porter,NaN,western,https://en.wikipedia.org/wiki/The_Great_Train_...,The film opens with two bandits breaking into ...,1,[action],[action],the film opens with two bandits breaking into ...
7,1904,The Suburbanite,American,Wallace McCutcheon,NaN,comedy,https://en.wikipedia.org/wiki/The_Suburbanite,The film is about a family who move to the sub...,1,[comedy],[comedy],the film is about a family who move to the sub...
8,1905,The Little Train Robbery,American,Edwin Stanton Porter,NaN,unknown,https://en.wikipedia.org/wiki/The_Little_Train...,The opening scene shows the interior of the ro...,1,[<unknown>],[],the opening scene shows the interior of the ro...
9,1905,The Night Before Christmas,American,Edwin Stanton Porter,NaN,unknown,https://en.wikipedia.org/wiki/The_Night_Before...,Scenes are introduced using lines of the poem....,1,[<unknown>],[],scenes are introduced using lines of the poem....
10,1906,Dream of a Rarebit Fiend,American,Wallace McCutcheon and Edwin S. Porter,NaN,short,https://en.wikipedia.org/wiki/Dream_of_a_Rareb...,The Rarebit Fiend gorges on Welsh rarebit at a...,1,[short],[],the rarebit fiend gorges on welsh rarebit at a...
11,1906,From Leadville to Aspen: A Hold-Up in the Rockies,American,Francis J. Marion and Wallace McCutcheon,NaN,short action/crime western,https://en.wikipedia.org/wiki/From_Leadville_t...,The film features a train traveling through th...,1,[short|action|crime|action],[],the film features a train traveling through th...
12,1906,Kathleen Mavourneen,American,Edwin S. Porter,NaN,short film,https://en.wikipedia.org/wiki/Kathleen_Mavourn...,Irish villager Kathleen is a tenant of Captain...,1,[short],[],irish villager kathleen is a tenant of captain...
13,1907,Daniel Boone,American,Wallace McCutcheon and Ediwin S. Porter,"William Craven, Florence Lawrence",biographical,https://en.wikipedia.org/wiki/Daniel_Boone_(19...,Boone's daughter befriends an Indian maiden as...,1,[biography],[biography],boone daughter befriends an indian maiden as ...
14,1907,How Brown Saw the Baseball Game,American,Unknown,Unknown,comedy,https://en.wikipedia.org/wiki/How_Brown_Saw_th...,Before heading out to a baseball game at a nea...,1,[comedy],[comedy],before heading out to a baseball game at a nea...
15,1907,Laughing Gas,American,Edwin Stanton Porter,"Bertha Regustus, Edward Boulden",comedy,https://en.wikipedia.org/wiki/Laughing_Gas_(fi...,The plot is that of a black woman going to the...,1,[comedy],[comedy],the plot is that of a black woman going to the...
16,1908,The Adventures of Dollie,American,D. W. Griffith,"Arthur V. Johnson, Linda Arvidson",drama,https://en.wikipedia.org/wiki/The_Adventures_o...,On a beautiful summer day a father and mother ...,1,[drama],[drama],on a beautiful summer day a father and mother ...
17,1908,The Black Viper,American,D. W. Griffith,D. W. Griffith,drama,https://en.wikipedia.org/wiki/The_Black_Viper,A thug accosts a girl as she leaves her workpl...,1,[drama],[drama],a thug accosts a girl as she leaves her workpl...
18,1908,A Calamitous Elopement,American,D.W. Griffith,"Harry Solter, Linda Arvidson",comedy,https://en.wikipedia.org/wiki/A_Calamitous_Elo...,A young couple decides to elope after being ca...,1,[comedy],[comedy],a young couple decides to elope after being ca...
19,1908,The Call of the Wild,American,D. W. Griffith,Charles Inslee,adventure,https://en.wikipedia.org/wiki/The_Call_of_the_...,A white girl (Florence Lawrence) rejects a pro...,1,[action],[action],a white girl (florence lawrence) rejects a pro...
20,1908,A Christmas Carol,American,Unknown,Tom Ricketts,drama,https://en.wikipedia.org/wiki/A_Christmas_Caro...,No prints of the first American film adaptatio...,1,[drama],[drama],no prints of the first american film adaptatio...
21,1908,The Fight for Freedom,American,D. W. Griffith,"Florence Auer, John G. Adolfi",western,https://en.wikipedia.org/wiki/The_Fight_for_Fr...,The film opens in a town on the Mexican border...,1,[action],[action],the film opens in a town on the mexican border...
22,1909,At the Altar,American,D. W. Griffith,Marion Leonard,drama,https://en.wikipedia.org/wiki/At_the_Altar,A rejected admirer sets up a trap to kill his ...,1,[drama],[drama],a rejected admirer sets up a trap to kill his ...
23,1909,A Drunkard's Reformation,American,D. W. Griffith,Arthur V. Johnson,drama,https://en.wikipedia.org/wiki/A_Drunkard%27s_R...,"John Wharton, the husband of a true and trusti...",1,[drama],[drama],"john wharton, the husband of a true and trusti..."
24,1909,The Golden Louis,American,D. W. Griffith,NaN,drama,https://en.wikipedia.org/wiki/The_Golden_Louis,An old woman sends a girl begging in the stree...,1,[drama],[drama],an old woman sends a girl begging in the stree...

In [60]:
cleanedDataset = moviesData[moviesData.Selected_Genre.str.len()>0]
cleanedDataset['Selected_Genre'] = cleanedDataset.Selected_Genre.apply(''.join)
totalNumberOfGenres = cleanedDataset[['Selected_Genre','TotalCount']].groupby(['Selected_Genre'], as_index=False).count().shape[0]
cleanedDataset = cleanedDataset.drop('TotalCount', 1)
cleanedDataset.to_csv('CleanedDataset.csv',sep=',')

cleanedDataset.drop(['Release Year', 'Origin/Ethnicity', 'Director', 'Cast', 'Wiki Page', 'Plot', 'Genre', 'Edited_Genre'], axis=1, inplace=True)
cleanedDataset.to_csv('CleanedDatasetForML.csv',sep=',')

/Users/macbookpro/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [61]:
totalNumberOfGenres

25